# docker-compose up -d
version: '2'
services: 
    microservice:
        build: .
        image: go_fib_gen_api:1.0.0-alpine
        environment: 
        - PORT=5005
        ports: 
        - "5005:5005"
        
    # nginx:
    #     image: "nginx:1.12"
    #     ports: 
    #     - "8080:80"
    #     links: 
    #     - microservice